### ISSUE TITLE
Enable community narrative around efforts

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#104]
As the president of FLRC and race director, I want to encourage people to build community online as well as offline since we can't always run together. To promote that in the Challenge, I'd like to allow people to link photos or descriptions of their runs. While it would be cool to link to Strava (not that I can see any way to do that while tying to our courses), I don't want to recreate Strava, especially since we have systems for photos (shared Yogile photo library) and text (FLRC forum) already. 

My thinking is that each effort would have one or two URL fields where people could paste URLs for photos they uploaded or posts they made, with each being awarded a community point to reward the behavior. For security, I'd suggest that only URLs to the appropriate sites be accepted.

Acceptance criteria:
* Some way to link to Yogile photos and forum posts
* Tracking of community points associated with the posts

**Comment by SteveDesmond-ca** [comment]
It's there any budget for these new features? It may be a little crunched otherwise.

I think the lowest friction version would be to have a Google Forms link in the menu, with a form containing:
- name
- course drop-down
- date selector
- group run checkbox
- local business checkbox
- social media link field

I haven't confirmed all the details but that all should be simple enough to pull in from their API, and we can do some sort of matching logic to link the run.

**Comment by adamengst** [comment]
Adam Pacheck had some good ideas on our run today:

* For group runs, rather than making it something that people enter manually, what if we just detect it by people whose start or end times are within a certain window? That would put the burden on people to scan together or at least coordinate their manual entry, but eliminates a separate step for saying that a run was part of a group. Technically, that could also enable different numbers of points based on the number of people, since it would be auto-detected. 

* For run reports and local business support, what about using tags in Discourse? We could create specific tags and then people could add them to a post—which is authenticated, by definition, so we know who it goes to—to get community points. The Discourse API is here—the main trick might be matching a Discourse user with a person in the leaderboard, but I can edit everyone's "real name" to ensure it matches if need be.

https://docs.discourse.org/

As far as budget goes, let's see what we end up deciding to do in part, but I think I can budget $500 for it comfortably as long as we break 100 registrants.

**Comment by SteveDesmond-ca** [comment]
I like both of those, because they push people towards using the existing tools (QR scanning vs manual entry, and the FLRC forum -- plus since the forum is self-hosted, we don't need to worry about API rate limiting or usage overrun costs, which was something on my mind for the Google Forms idea)...thanks, @apacheck!

**Comment by adamengst** [comment]
Yeah, it was a classic example of a fresh perspective!

**Comment by apacheck** [comment]
Glad it could help!

**Comment by SteveDesmond-ca** [comment]
@adamengst How does this sound as a test to set up:
- create a new "2022 Challenge Community" (or something similar) forum, currently just visible to challenge admins
- create a new topic for each course (currently just the test course)
- any post in the topic with a link and/or attachment will give a "community narrative" point 
- match the run based on the user's name, course/topic ID (in app config) and date of post (will pick first run of the day to give a point to)
- limit to one community narrative point per user per course per day (so max 10 per day for each athlete)

**Comment by adamengst** [comment]
That sounds like a plan! I've created the test category, accessible only to challenge-admins for now.

https://forum.fingerlakesrunners.org/c/2022-challenge-community/31

Assuming this works, we might want to stick with our existing FLRC Challenge category and just specify 10 topics in it for narrative posts. I fear that if we have a separate narrative post category, people will just get confused about where to post questions and other things. 

I'm not sure that posts in the appropriate topics need a link or attachment; if they're just a run report, they could be straight text.

**Comment by SteveDesmond-ca** [comment]
Yep, the existing category should be fine, and maybe pin the narrative topics, or give them a special tag so they stand out?

I'm mostly thinking of how to differentiate between a post worth points and someone replying to a points-worthy post.

Maybe since Markdown is "simple enough" we can just say users need to add `## Narrative` as a header to their report, and `## Local Business` with a brief description of where they went?

**Comment by adamengst** [comment]
Pinning the topics in the existing category should work well. There's no direct way in Discourse to tag a post (as opposed to a topic), though this topic suggests bookmarks and badges, along with unique words as you suggested. There also seems to be a custom field capability, though I don't understand that as yet.

https://meta.discourse.org/t/how-do-i-tag-a-post/54193

**Comment by adamengst** [comment]
I wonder if we can use Discourse topic templates to help people with the formatting:

https://meta.discourse.org/t/what-are-topic-templates/38295

**Comment by SteveDesmond-ca** [comment]
Ooh, the "Reply Template theme component" sounds promising

**Comment by SteveDesmond-ca** [comment]
Implemented as of 855d8ad
