### ISSUE TITLE
Award community points for supporting a local business as part of a run

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#105]
As race director and a supporter of local businesses, I'd like to encourage runners to support businesses, particularly food purveyors, as part of their runs. To do that, I'd suggest that each effort have a checkbox for "Supported local business" or something like that. Manual selection of that checkbox would award a community point, as with the other approaches.

Acceptance criteria:
* Some way to indicate, on the honor system, that a run was associated with support of a local business
* Awarding and tracking of the related community points

**Comment by adamengst** [comment]
Sounds like a worthy approach to try! I'm not too familiar with BBCode, but it seems that Discourse has a BBCode plugin, and I wonder if that can automatically style certain BBCode tags.

https://meta.discourse.org/t/best-course-of-action-on-supporting-custom-bbcode/148941

**Comment by SteveDesmond-ca** [comment]
I'll see how the Markdown solution looks first, since that's definitely going to be simpler and cleaner, but will keep BBCode in mind as a backup

**Comment by SteveDesmond-ca** [comment]
@adamengst Since our test topic is in a locked category, I'll need an API key to access it externally as an authenticated user -- this should be doable from the admin area, under the "API" tab. See https://meta.discourse.org/t/how-to-create-an-api-key-on-the-admin-panel/87383 for details. You can set me as the user if necessary. We won't need this for the real category, since that will be publicly visible.

Please email this API key directly, rather than including it here, as it will give anyone who has it access to the forum as that user.

**Comment by SteveDesmond-ca** [comment]
Thanks for the API key @adamengst, I confirmed it's working and will keep digging into the implementation for this tomorrow.

**Comment by SteveDesmond-ca** [comment]
Implemented as of 855d8ad
