### ISSUE TITLE
Tie for Sweet 1600 Fastest results in incorrect age group award

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#125]
If you look at the [Awards](https://challenge.fingerlakesrunners.org/Awards) page, you'll see that Margaret Frank is getting both Sweet 1600 (Fastest), which is right because she tied with Liz Hartman, and the Sweet 1600 30-39, which is wrong, since she should drop out of the age competition for being an overall winner. Obviously an edge case on the tie, but Jilene Demont should be the winner.

It is working correctly in the 40-49 age group, where Michelle Woods is the age group winner because Liz drops out from being the overall winner. It may have been doubly confused because Liz changed age groups midway.

If it's too hard to fix this, it's really no problem to set Jilene up and Margaret down manually in the report to Ian.

**Comment by SteveDesmond-ca** [comment]
Yep, I see it: https://github.com/FingerLakesRunnersClub/Leaderboards/blob/7560c6fde85ed0c96ff8050caf7a114500d86133/Core/Reports/AwardsViewModel.cs#L79

Should be an easy-ish fix, I'll see what I can do tomorrow.

**Comment by SteveDesmond-ca** [comment]
:sob: of course, Liz's fastest 30-39 time is tied with Jilene's, so the easy-ish fix I was thinking of doesn't work!

I'd say to get the list to Ian ASAP, just manually change it, and I can push a properly-tested solution out tomorrow.

**Comment by SteveDesmond-ca** [comment]
Fix has been pushed as a78c4b8, but not yet deployed since it'll take several minutes for the community posts to fully repopulate, given Discourse's heavy API throttling (possibly remedied via [its config](https://meta.discourse.org/t/global-rate-limits-and-throttling-in-discourse/78612)) and until then, community points will be incomplete.

@adamengst lmk when a good time to deploy would be when we can handle a few minutes of incorrect community points while they all redownload.

**Comment by SteveDesmond-ca** [comment]
Successfully deployed and updated

**Comment by adamengst** [comment]
Sigh! Tomorrow or the next day is fine—I have the track meet to run today.
