### ISSUE TITLE
Automated deployment

### ISSUE THREAD

**Issue by SteveDesmond-ca** [FingerLakesRunnersClub/Leaderboards#224]
As a FLRC server admin, I want to get automated updates to the leaderboard apps without it hogging all my server resources, so that the forum can keep running undisturbed.

Acceptance criteria:
- production builds no longer happen on the production server
- Docker images are built and pushed to Docker Hub via GitHub Actions
- a "Deployment" GitHub Action workflow is created for pulling the images onto production and restarting the Docker Compose services
- the "Deployment" workflow can be manually triggered by a non-developer admin

**Comment by adamengst** [comment]
Ooo, I like you more than I used to. This should make life easier for all of us, and I was just about to ask you if you thought beefing up the DigitalOcean VPS would be worth it, since the forum has been bogging down quite a bit of late. I'll keep an eye on it to see if this makes any difference on a regular basis.
